### ISSUE TITLE
Consider migrating to github.com/adobedocs

### ISSUE THREAD

**Issue by filmaj** [AdobeDocs/commerce-cif-documentation#2]
FYI @stevengill - I am not sure on the exact process around open sourcing documentation but I am aware that we want to keep all adobe docs under the adobedocs organization.

Post-break let's work with @cjelger and his team to move this repo to the appropriate place.

For context: there was [an internal issue](https://jira.corp.adobe.com/browse/DEVEP-765) the team needed to solve quickly before the Christmas break, and so this repo was created to address that, and thus the team didn't go through our [form](https://git.corp.adobe.com/pages/OpenSourceAdvisoryBoard/opensource_submission).

**Comment by macdonst** [comment]
Yeah, we can transfer this repo to the AdobeDocs org without any impact on folks who already have bookmarked this repo (or have git remotes setup). Since the repo doesn't have the Kirby manifest file setup yet, I suggest we move it before the break and just give @kgera a heads up.

**Comment by guillaumecarlino** [comment]
Please go ahead and migrate it, this one was just created earlier today. I'll ping @kgera on the jira issue associates with the repo.

**Comment by cjelger** [comment]
Sorry guys for having created the repo too quickly: @guillaumecarlino couldn't create it so I did it for him, so he should decide for everything. ;-)

**Comment by stevengill** [comment]
I have migrated the repo to AdobeDocs. @guillaumecarlino I'm giving you admin access to this repo
